#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pig.Resource", IsApplication=true)]

namespace Pig
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Die1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Die2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Die3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Die4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Die5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Die6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int TxtView1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int TxtView2 = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int currentScore = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int dieImageView = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int endBtn = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int gameFragment = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout3 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout4 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout6 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout7 = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout9 = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int menuFragment = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int newGameBtn = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int pOneNameTxtBox = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int pTwoNameTxtBox = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int playerOneScore = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int playerOneTxtView = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int playerTwoScore = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int playerTwoTxtView = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int relativeLayout1 = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int rollBtn = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int startGameBtn = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int textView1 = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int textView8 = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int turnText = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameFrag = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuFrag = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
